<<<<<<< HEAD
Collecting parallel
  Downloading parallel-0.2.5.tar.gz (57 kB)
     ---------------------------------------- 57.3/57.3 kB 299.9 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\mark\AppData\Local\Temp\pip-install-c1io7jr1\parallel_2c71e82ce79541a18725121d7a65b9c0\setup.py", line 5, in <module>
          import pprocess
        File "C:\Users\mark\AppData\Local\Temp\pip-install-c1io7jr1\parallel_2c71e82ce79541a18725121d7a65b9c0\pprocess.py", line 255
          raise AcknowledgementError, obj
                                    ^
      SyntaxError: invalid syntax
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
=======
Collecting parallel
  Downloading parallel-0.2.5.tar.gz (57 kB)
     ---------------------------------------- 57.3/57.3 kB 299.9 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\mark\AppData\Local\Temp\pip-install-c1io7jr1\parallel_2c71e82ce79541a18725121d7a65b9c0\setup.py", line 5, in <module>
          import pprocess
        File "C:\Users\mark\AppData\Local\Temp\pip-install-c1io7jr1\parallel_2c71e82ce79541a18725121d7a65b9c0\pprocess.py", line 255
          raise AcknowledgementError, obj
                                    ^
      SyntaxError: invalid syntax
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
>>>>>>> e9106edc9b38e9c75306c14d31201c271f0b9a3e
hint: See above for details.